name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest-stable

    - name: Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: |
        bundle exec fastlane scan --code_coverage true
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
